export * as grpc from '@grpc/grpc-js'
export * from '../generated/category_pb'
export * from '../generated/inventory_pb'
export * from '../generated/product_pb'
export * from '../generated/service_grpc_pb'
export * from '../generated/service_pb'
